 # default 설정
spring:
  application:
    name: gasipan
  config:
    use-legacy-processing: true
  profiles:
    active: localhost
  datasource: # db 설정
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/sample_db
    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/sample_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: gasipan
    password: gasipan

#logging
logging:
 config: classpath:logback-spring.xml

# port 설정
server: 
  port: 8088
  
# mapper 스캔 위치
mybatis:
  mapper-locations: classpath:mapper/**/*.xml 
  configuration:
    map-underscore-to-camel-case: true

--- # localhost
# 로그 파일 경로
log:
  path: D:\@\gasipan\log
attached:
  upload:
    root: D:\@\gasipan\attached_file
...

--- # dev
spring:
 profiles:
  - development
log:
 path : C:\@\gasipan\log
...
